version = 0.1
[default.deploy.parameters]
stack_name = "url-shortener-stack"
s3_bucket = "url-shortner-bucket-rohit"
resolve_s3 = false
s3_prefix = "url-shortener-stack"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
