AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UrlShortener
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../backend
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
          BASE_URL: "https://short.ro.com"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: GET
        ShortenUrl:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
        RedirectUrl:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: GET
      

  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlTable
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiGatewayInvokeUrl:
    Description: "Base URL for API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
