AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: UrlShortenerApi
      StageName: Prod

  UrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UrlShortenerService
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../backend
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
          BASE_URL: https://0q8pmbhw80.execute-api.ap-south-1.amazonaws.com/Prod
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        ShortenUrl:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
            RestApiId: !Ref ApiGateway

        ShortenUrlOptions:
          Type: Api
          Properties:
            Path: /shorten
            Method: OPTIONS
            RestApiId: !Ref ApiGateway

        RedirectUrl:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: GET
            RestApiId: !Ref ApiGateway

        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway

  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiGatewayInvokeUrl:
    Description: "Base URL for API Gateway"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
